site_name: Stratos Documentation
site_url: https://docs.thestratos.org
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  logo: assets/logo.png
  favicon: assets/favicon.ico

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: teal
      accent: teal

nav:
  - Home: index.md
  - Introduction:
    - About Stratos: docs-about/about-stratos.md
    - STOS Token Economy: docs-about/stratos-token-economy.md
    - Updates: docs-about/changes.md
  - Stratos Chain:
    - HOWTOs:
      - Full-Chain Node: docs-stratos-chain/setup-and-run-a-stratos-chain-full-node.md
      - Become a Validator: docs-stratos-chain/how-to-become-a-validator.md
      - Use of State Sync: docs-stratos-chain/how-to-start-with-state-sync.md
      - Full-Chain as REST/gRPC: docs-stratos-chain/how-to-setup-rest-grpc-full-chain.md
      - Use the Bridge on Testnet: docs-stratos-chain/how-to-use-bridge-testnet.md
      - Mainnet Bridge and Staking: docs-stratos-chain/mainnet-bridge-and-staking.md
    - Operating:
      - stchaind Commands Part 1: docs-stratos-chain/stchaind-commands-part-1.md
      - stchaind Commands Part 2: docs-stratos-chain/stchaind-commands-part-2.md
      - gRPC Queries: docs-stratos-chain/stratos-chain-grpc-queries.md
      - REST APIs: docs-stratos-chain/stratos-chain-rest-apis.md
      - Network: docs-stratos-chain/network.md
    - EVM:
      - Node config: docs-evm/node-config.md  
      - Deploying on Stratos:
        - Using Hardhat: docs-evm/deploy-smart-contracts/hardhat.md
        - Using Truffle: docs-evm/deploy-smart-contracts/truffle.md
      - Wallets:
        - Hello MetaMask: docs-evm/wallets/metamask/hello.md
        - Configure Stratos on MetaMask: docs-evm/wallets/metamask/configure-on-metamask.md
        - Multiple Accounts: docs-evm/wallets/metamask/multiple-accounts.md
        - STOS Gas token: docs-evm/wallets/metamask/gas-token.md
      - Available dapps: docs-evm/available-dapps.md
  - Resource Node:
    - HOWTOs:
      - SDS Resource Node: docs-resource-node/setup-and-run-a-sds-resource-node.md
      - SDS Update to v12: docs-resource-node/sds-update-v12.md
      - Migrate IPFS: docs-resource-node/sds-ipfs-handbook.md
      - Video Streaming: docs-resource-node/sds-video-streaming-handbook.md
    - Operating:
      - ppd Commands: docs-resource-node/ppd-terminal-subcommands.md
      - SDS RPC: docs-resource-node/sds-rpc-for-file-operation.md
    - Examples:
      - RPC Client: docs-resource-node/rpc-client.md

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/chrome
      link: https://thestratos.org
    - icon: fontawesome/brands/telegram
      link: https://t.me/StratosOfficial
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/tpQGpC2nMh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Stratos_Network 
    - icon: fontawesome/brands/medium
      link: https://stratos-network.medium.com/ 
    - icon: fontawesome/brands/github
      link: https://github.com/stratosnet

markdown_extensions:
  - toc:
      permalink: "🔗&#xFE0E;"
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - meta
  - tables
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

validation:
  unrecognized_links: ignore    

copyright: <p> &copy; 2021-<script>document.write(new Date().getFullYear())</script> Stratos Network</p>
